language: java

script: ./build.sh jar testTravis

cache:
  directories:
    - $HOME/.m2/repository

os: linux

jobs:
  include:
    - jdk: openjdk11
      dist: trusty
      group: edge
      before_script:
        - "cd h2"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx512m"
    - jdk: oraclejdk8
      dist: trusty
      group: edge
      before_script:
        - "cd h2"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx512m"
